// Generated by gencpp from file obj_tracker/strNum.msg
// DO NOT EDIT!


#ifndef OBJ_TRACKER_MESSAGE_STRNUM_H
#define OBJ_TRACKER_MESSAGE_STRNUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obj_tracker
{
template <class ContainerAllocator>
struct strNum_
{
  typedef strNum_<ContainerAllocator> Type;

  strNum_()
    : some_string()
    , some_int(0)  {
    }
  strNum_(const ContainerAllocator& _alloc)
    : some_string(_alloc)
    , some_int(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _some_string_type;
  _some_string_type some_string;

   typedef uint32_t _some_int_type;
  _some_int_type some_int;




  typedef boost::shared_ptr< ::obj_tracker::strNum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obj_tracker::strNum_<ContainerAllocator> const> ConstPtr;

}; // struct strNum_

typedef ::obj_tracker::strNum_<std::allocator<void> > strNum;

typedef boost::shared_ptr< ::obj_tracker::strNum > strNumPtr;
typedef boost::shared_ptr< ::obj_tracker::strNum const> strNumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obj_tracker::strNum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obj_tracker::strNum_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace obj_tracker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'obj_tracker': ['/home/kentbot/catkin_ws/src/obj_tracker/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::obj_tracker::strNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obj_tracker::strNum_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obj_tracker::strNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obj_tracker::strNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obj_tracker::strNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obj_tracker::strNum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obj_tracker::strNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f96250af5e3163f91ec8bac6b3aa2d91";
  }

  static const char* value(const ::obj_tracker::strNum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf96250af5e3163f9ULL;
  static const uint64_t static_value2 = 0x1ec8bac6b3aa2d91ULL;
};

template<class ContainerAllocator>
struct DataType< ::obj_tracker::strNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obj_tracker/strNum";
  }

  static const char* value(const ::obj_tracker::strNum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obj_tracker::strNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string some_string\n\
uint32 some_int\n\
";
  }

  static const char* value(const ::obj_tracker::strNum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obj_tracker::strNum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.some_string);
      stream.next(m.some_int);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct strNum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obj_tracker::strNum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obj_tracker::strNum_<ContainerAllocator>& v)
  {
    s << indent << "some_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.some_string);
    s << indent << "some_int: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.some_int);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJ_TRACKER_MESSAGE_STRNUM_H
